# Generated by Django 2.2 on 2021-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_numbers",
                    models.IntegerField(verbose_name="Запрашиваемый ОГРН/ИНН"),
                ),
                ("answer", models.CharField(max_length=300, verbose_name="Ответ")),
                (
                    "date_request",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
            ],
        ),
    ]
